### ISSUE TITLE
Interaction with yeoman

### ISSUE THREAD

**Issue by Chris2011** [awegmann/consoleui#19]
Hi,

I was searching for a java wrapper for yeoman, so that I can run yeoman generators via java and interact via java with the original generator. Now I found your project and I was wondering, whether I can interact with your implementation with yeoman generators? Is this possible? My plan is to implement Yeoman into NetBeans but atm the IDE hangs because of the missing user input that is needed.

Cheers

Chris

**Comment by awegmann** [comment]
Hi Chris.

To be true, consoleUI was inspired by yeoman and the underlying inquirer.js. I wrote it, because I wanted to use it inside gradle builds. Unfortunately that didn't work well and that's why I never really used it for that purpose. 

So, now to your question. consoleUI is definitely not a drop in replacement for anything in the yeoman software. It looks like the same, but is a completely different implementation. Of course, you can use it as a frontend for something written in Java that executes the yeoman as long as yeoman can be invoked with all necessary parameters and without interactive mode. But I guess you will have the same problem as you have by directly invoking yeoman - you need an ANSI terminal.

If you want to create wrappers for Yeoman in Netbeans, wouldn't it be better to create a graphical UI and call Yeoman with the requested parameters? Another option would be to use a terminal implementation (maybe written in Java) and use this for user interaction. I'm using IntelliJ and I know that JetBrains maintains an excellent terminal implementation which is integrated in their products. But I think it's not really open source. Maybe Netbeans already has something like that?

Best regards.
 Andreas

**Comment by Chris2011** [comment]
Hey, I was inspired by the yeoman implementation for in WebStorm. Yes, they pass the parameters but they use the interactive mode of the generator, because you don't know what the user wants so it is up to the user for that to choose (https://cloud.githubusercontent.com/assets/795658/11398374/6e38c782-9380-11e5-9892-dfc8f44a58d7.gif). So yes it was first my impression to make a NetBeans Java wrapper for yeoman to interact with it, because it blocks the whole IDE and is waiting for user input as you can read it here: https://github.com/GeertjanWielenga/YoNetBeans/issues/2

Luckily the developer from the WebStorm Team for the Yeoman integration commented and gave me this information:

`The API http://yeoman.io/authoring/integrating-yeoman.html is used: we start a separate yeoman-wrapper node.js process and communicate with the process using simple stdin/stdout.`

So this is why I wanted to create a Java wrapper for everyone, not only for NetBeans. But maybe it would be better to make that in NetBeans.

Thx for the insights, I'm searching for every little help, that I can find to make this goal happen since years, but my knowledge of the Java integration and communicating with other processes is not that good.


Cheers

Chris

**Comment by Chris2011** [comment]
It was not my intention to replace yeoman, I just wanted to know, whether this will help me using your java implementation to communicate with yeoman, but inside the interactive mode. But unfortunately you gave me the question that this is not really possible. So no problem at all :)

**Comment by awegmann** [comment]
As we discussed, ConsoleUI is not the tool for your problem...

**Comment by Chris2011** [comment]
Thx for your help :)
