### ISSUE TITLE
Wow -- exactly what I was looking for!

### ISSUE THREAD

**Issue by MTyson** [awegmann/consoleui#2]
I too was searching for a Java Inquirer.js type thing.  I have gone down the road on JLine a ways, but as you know it has no ui support... looking forward to trying your project.

**Comment by awegmann** [comment]
Hi. Sorry for the very poor documentation at the moment. You can take a look at `de.codeshelf.consoleui.Basic` which is a small demo how to use the API. Which platform are you using? Linux? Windows? Mac?

Releases can be found on mavencentral 

[https://search.maven.org/#artifactdetails%7Cde.codeshelf.consoleui%7Cconsoleui%7C0.0.9%7Cjar](https://search.maven.org/#artifactdetails%7Cde.codeshelf.consoleui%7Cconsoleui%7C0.0.9%7Cjar)

**Comment by MTyson** [comment]
I am running Windows, primarily on git bash.  

I'm curious if you've got JLine's auto-completer working so it can change during a run (that is, you can change it for a new dialog inside the same reader)?  Also, I want to use consoleui as part of an ongoing JLine console... possible? 

I'm looking at consoleui.basic right now.

**Comment by MTyson** [comment]
It just ran basic, and it looks awesome.  It seems to freeze at the 'how do you want to pay' question in both cmd and gitbash.

**Comment by MTyson** [comment]
BTW, I just made some small changes to docs and can push it to a branch if you want.

**Comment by awegmann** [comment]
Hm. I'm developing on a Mac and Windows is not my primary platform. I can try to test it again (on Windows 7). 
JLines auto-complete can be added. As far as I remember for each input prompt. So you should be able to use a filename completer for one input and a simple string array completer for another input prompt.

I made some experience to use consoleUI together with gradle. This was my primary goal to use it in gradle build jobs to do interactive input. Unfortunately I didn't worked well. Maybe because gradle uses JLine and JAnsi itself. Checkbox promt and list promt worked well, input promt not. :-(

BTW: I added gitter chat. Maybe it's easier to communicate there.

**Comment by awegmann** [comment]
Did you fork the repository? I would be pleased to get pull request for consoleUI. I already made a branch for documentation.

**Comment by mainrs** [comment]
Can contribute to by documenting stuff. Got some spare time here and there.

**Comment by awegmann** [comment]
@SirWindfield Yes, of course. Would be nice. The more contributors the better.

**Comment by mainrs** [comment]
One question: Can I remove the User and Date from the Javadoc of all those files? Adding a license to the top of each file (for example an Apache 2 License or even an open source software license) would do the same without disturbing the Javadoc.
